---
name: Publish Pages
on:
  push:
    tags:
      - v*
permissions:
  contents: write
jobs:
  publish-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: npm
      - name: Install and Build
        run: |
          npm ci
          npm run docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
