---
name: Publish Pages
on:
  push:
    tags:
      - v*
permissions:
  contents: read
  id-token: write
  pages: write
jobs:
  publish-pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json
      - name: Configure Pages
        if: ${{ !env.ACT }}
        uses: actions/configure-pages@v5
      - name: Install and Build
        run: |
          bun install --frozen-lockfile
          bun run docs
      - name: Upload Pages Artifact
        if: ${{ !env.ACT }}
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs
      - name: Deploy
        if: ${{ !env.ACT }}
        id: deployment
        uses: actions/deploy-pages@v4
