---
name: Publish Pages
on:
  push:
    tags:
    - v*
jobs:
  publish-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "15"

    - name: Install and Build
      run: |
        npm install --no-save
        npm run docs

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: docs
