---
name: Run Tests
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: "15"

    - name: Install and Test
      run: |
        npm install --no-save
        npm run test
